apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: we3n8tpkp-nodejs 
  janus-idp.io/tekton: we3n8tpkp-nodejs
  backstage.io/kubernetes-id: we3n8tpkp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: we3n8tpkp-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml