apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: we3n8tpkp-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.clusterpool-ctmp8.rhtap.devcluster.openshift.com/rhtap/rhtap-qe-nodejs:2d661543efbfb317d7e06edefbc763733e34acd0@sha256:fb66ac735646d2196cbbe225ec42870b54081a482cfa839ff8aad8619c285335
          name: container-image
