apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: we3n8tpkp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: we3n8tpkp-nodejs 
  name: we3n8tpkp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: we3n8tpkp-nodejs 
